{% set name = "matid" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matid-{{ version }}.tar.gz
  sha256: b89fa51e15cb697880ec7127095b87b42a879ecb2f6e697f433555a8c0c47caa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - pybind11
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  run:
    - ase
    - chronic
    - future
    - networkx >=2.4
    - numpy
    - python
    - pybind11
    - scipy
    - scikit-learn
    - spglib >=1.15.0

test:
  imports:
    - matid
    - matid.classification
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://singroup.github.io/matid/
  license: Apache-2.0
  license_family: Other
  license_file: LICENSE
  summary: MatID is a python package for identifying and analyzing atomistic systems based on their structure.
  description: |
    MatID is a python package for identifying and analyzing atomistic 
    systems based on their structure. MatID is designed to help 
    researchers in the automated analysis and labeling of atomistic 
    datasets.
  doc_url: https://singroup.github.io/matid/
  dev_url: https://github.com/SINGROUP/matid

extra:
  recipe-maintainers:
    - jan-janssen
    - lauri-codes
