{% set name = "matid" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matid-{{ version }}.tar.gz
  sha256: 915977090005e46a65a56b536d6a4be993e10a38318c07e5f08ccbfabb0a2911

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - ase
    - chronic
    - future
    - networkx >=2.4
    - numpy
    - python >=3.5
    - scipy
    - scikit-learn
    - spglib >=1.15.0

test:
  imports:
    - matid
    - matid.classification
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://singroup.github.io/matid/
  license: Apache-2.0
  license_family: Other
  license_file: LICENSE
  summary: MatID is a python package for identifying and analyzing atomistic systems based on their structure.
  description: |
    MatID is a python package for identifying and analyzing atomistic 
    systems based on their structure. MatID is designed to help 
    researchers in the automated analysis and labeling of atomistic 
    datasets.
  doc_url: https://singroup.github.io/matid/
  dev_url: https://github.com/SINGROUP/matid

extra:
  recipe-maintainers:
    - jan-janssen
