{% set name = "matid" %}
{% set version = "2.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/matid-{{ version }}.tar.gz
  sha256: 7cb5343fefe6bbddead228029cdbd4987df9e22779e50c21c238d641adeee651

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - pybind11
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  run:
    - ase
    - chronic
    - future
    - networkx >=2.4
    - numpy
    - python
    - pybind11
    - scipy
    - scikit-learn
    - spglib >=2.0.0

test:
  imports:
    - matid
    - matid.classification
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://singroup.github.io/matid/
  license: Apache-2.0
  license_family: Other
  license_file: LICENSE
  summary: MatID is a python package for identifying and analyzing atomistic systems based on their structure.
  description: |
    MatID is a python package for identifying and analyzing atomistic 
    systems based on their structure. MatID is designed to help 
    researchers in the automated analysis and labeling of atomistic 
    datasets.
  doc_url: https://singroup.github.io/matid/
  dev_url: https://github.com/SINGROUP/matid

extra:
  recipe-maintainers:
    - jan-janssen
    - lauri-codes
